openapi: 3.0.0
info:
  title: Restful Booker API
  version: 1.0.0
paths:
  /auth:
    post:
      summary: CreateToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
  
  /booking:
    post:
      summary: CreateBooking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstname:
                  type: string
                lastname:
                  type: string
                totalprice:
                  type: integer
                depositpaid:
                  type: boolean
                bookingdates:
                  type: object
                  properties:
                    checkin:
                      type: string
                      format: date
                    checkout:
                      type: string
                      format: date
                additionalneeds:
                  type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  bookingid:
                    type: integer
                  booking:
                    type: object
                    properties:
                      firstname:
                        type: string
                      lastname:
                        type: string
                      totalprice:
                        type: integer
                      depositpaid:
                        type: boolean
                      bookingdates:
                        type: object
                        properties:
                          checkin:
                            type: string
                            format: date
                          checkout:
                            type: string
                            format: date
                      additionalneeds:
                        type: string

  /booking/{id}:
    get:
      summary: GetBookingIDs
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  firstname:
                    type: string
                  lastname:
                    type: string
                  totalprice:
                    type: integer
                  depositpaid:
                    type: boolean
                  bookingdates:
                    type: object
                    properties:
                      checkin:
                        type: string
                        format: date
                      checkout:
                        type: string
                        format: date
                  additionalneeds:
                    type: string
    put:
      summary: UpdateBooking
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstname:
                  type: string
                lastname:
                  type: string
                totalprice:
                  type: integer
                depositpaid:
                  type: boolean
                bookingdates:
                  type: object
                  properties:
                    checkin:
                      type: string
                      format: date
                    checkout:
                      type: string
                      format: date
                additionalneeds:
                  type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  firstname:
                    type: string
                  lastname:
                    type: string
                  totalprice:
                    type: integer
                  depositpaid:
                    type: boolean
                  bookingdates:
                    type: object
                    properties:
                      checkin:
                        type: string
                        format: date
                      checkout:
                        type: string
                        format: date
                  additionalneeds:
                    type: string
    delete:
      summary: DeleteBooking
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        201:
          description: Booking Deleted

